version: '3.4'

services:
  rabbitmq:
    hostname: rabbitmq
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    hostname: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongo:27017/

  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: WebApi/Dockerfile
